title: "My AWS & Security Journey"
description: "A beginner-friendly space where I share my AWS mistakes, lessons, and growth in cloud security."
author: "Happyness Mwamba"

# Theme
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme

# Site settings
baseurl: "" # leave empty unless hosting under a subpath
url: "https://mwambaaaa.github.io" # replace with your actual GitHub Pages URL

# Build settings
markdown: kramdown

# Navigation (edit to match your pages)
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about/"
  - name: "Blog"
    link: "/blog/"
